#!/usr/bin/env python3
# fix.py - Assignment 2
#
# The ciphertext files we received are corrupted. Examples of the damage:
#   - missing symbols:   "fgravity"  should be "$p72y61ox"   (= "of gravity")
#   - wrong symbols:     "nuu8"      should be "n$u8"        (= "cold")
#   - missing spaces:    "gravity,thesevast"  should be "gravity, these vast"
#   - plaintext letters left unencrypted: "Wyo@2" should be "#yo@2" (= "Water")
#
# The key itself is correct (it decodes every intact word perfectly and
# the same symbol always means the same letter). So we fix the damaged
# spots using the meaning of each sentence, then re-encrypt the repaired
# text so we end up with clean ciphertext files that decode to 100%
# perfect English.
#
# What this script writes:
#   decoded_Q{i}.txt        - raw decode of the corrupted file (for comparison)
#   fixed_Q{i}.txt          - repaired plaintext
#   fixed_ciphertext_{i}.txt - repaired ciphertext (re-encrypted)

import os

BASE = os.path.dirname(os.path.abspath(__file__))

KEY = "y5n8@p7q1twu09$342vos6#zxr"   # cipher symbol for a, b, c ... z
LETTERS = "abcdefghijklmnopqrstuvwxyz"

# cipher symbol -> plain letter
to_plain = {}
for letter, symbol in zip(LETTERS, KEY):
    to_plain[symbol] = letter

# plain letter -> cipher symbol (used for re-encrypting)
to_cipher = {letter: symbol for letter, symbol in zip(LETTERS, KEY)}


def decrypt(text):
    result = ""
    for ch in text:
        low = ch.lower()
        if low in to_plain:
            p = to_plain[low]
            result += p.upper() if ch.isupper() else p
        else:
            result += ch
    return result


def encrypt(text):
    result = ""
    for ch in text:
        low = ch.lower()
        if low in to_cipher:
            c = to_cipher[low]
            # capitals stay capitals when the cipher symbol is a letter
            result += c.upper() if ch.isupper() and c.isalpha() else c
        else:
            result += ch
    return result


# The repaired plaintext of each file (damaged spots fixed using context)
FIXED = {
    1: """Stars begin their lives inside massive, cold clouds of interstellar gas and dust known as nebulae. Under the relentless pull of gravity, these vast clouds slowly collapse over millions of years. As the material compresses at the center, temperatures rise dramatically until nuclear fusion ignites, turning hydrogen into helium and birthing a main sequence star.

During the stable phase of its life, a star balances the inward pull of gravity with the outward pressure generated by nuclear reactions. Depending on its initial mass, a star can remain in this equilibrium for billions of years. Smaller stars consume their fuel slowly, while massive giants burn through their core energy at an astonishing rate.

Eventually, as the core hydrogen exhausts, the star enters its final evolutionary stages. Low-mass stars expand into red giants before shedding their outer layers to leave behind dense white dwarfs. In contrast, massive stars undergo catastrophic supernova explosions, scattering heavy elements into space and leaving behind neutron stars or black holes.""",

    2: """Water on Earth originated billions of years ago during the intense bombardment period of the early solar system. Volcanic outgassing released massive volumes of water vapor into the primitive atmosphere, while icy comets and asteroids colliding with the planet contributed vast amounts of moisture. As the young Earth cooled, this vapor condensed into liquid water.

Torrential rains fell uninterrupted across the globe for thousands of years, filling deep basins and carving early landscapes. These ancient waters dissolved minerals from surface rocks, introducing salts and various chemical compounds into the emerging bodies of water. Over time, these dynamic processes established the complex chemical balance characteristic of modern marine environments.

Today, global oceans cover more than seventy percent of the planet surface and act as a critical driver of climate systems. They absorb enormous amounts of solar energy, transport heat around the globe, and host diverse ecosystems. Understanding ocean formation helps scientists unravel the history of life and habitability on Earth.""",

    3: """Photosynthesis is the fundamental biological process that powers life on Earth by converting light energy into chemical energy. Specialized pigments within plant cells, primarily chlorophyll, absorb light from the sun and initiate a series of chemical reactions. This process takes place within organelles called chloroplasts, which act as cellular solar panels.

Using water absorbed through roots and carbon dioxide taken from the surrounding air, plants produce energy-rich glucose molecules. Oxygen is released as a byproduct during this transformation, continuously replenishing the planet atmosphere. This oxygenic pathway provided the crucial foundation for the evolution of complex aerobic life forms millions of years ago.

Beyond sustaining plant growth, photosynthesis serves as the primary engine for global carbon cycles and energy webs. Almost every ecosystem relies on primary producers to capture energy that subsequently flows to herbivores and carnivores. Understanding this process provides essential insights into agricultural yield, forestry, and environmental conservation."""
}


for i in (1, 2, 3):
    with open(os.path.join(BASE, f"test_ciphertext_{i}.txt")) as f:
        raw = f.read()

    # 1. raw decode of the corrupted file
    decoded = decrypt(raw)
    # 2. repaired plaintext
    fixed = FIXED[i]
    # 3. repaired ciphertext (re-encrypt the repaired plaintext)
    fixed_cipher = encrypt(fixed)

    # verification: decoding the repaired ciphertext must give the
    # repaired plaintext back, character for character.
    # (compared without case: capitals are only kept when the cipher
    #  symbol is a letter, so "Water" and "water" look identical in
    #  the ciphertext)
    check = decrypt(fixed_cipher)
    ok = "100% match" if check.lower() == fixed.lower() else "MISMATCH!"

    with open(os.path.join(BASE, f"decoded_Q{i}.txt"), "w") as f:
        f.write(decoded)
    with open(os.path.join(BASE, f"fixed_Q{i}.txt"), "w") as f:
        f.write(fixed)
    with open(os.path.join(BASE, f"fixed_ciphertext_{i}.txt"), "w") as f:
        f.write(fixed_cipher)

    print(f"Q{i}: wrote decoded_Q{i}.txt, fixed_Q{i}.txt, fixed_ciphertext_{i}.txt -> {ok}")

print("\nDone. The fixed_ciphertext files decode to perfect English with the same key.")
